name: Rodion Test v2

on: push

jobs:
  job_on_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: date

  job_on_windows:
    name: A windows job
    runs-on: windows-latest
    steps:
      - name: First step in windows job
        run: date

  final_job:
    name: Final job
    runs-on: windows-latest
    steps:
        - run: echo Hello World!!

        

